---
   
   - name: ensure easy_install is installed
     yum: name=python-setuptools-devel state=latest

   - name: ensure pip is installed
     easy_install: name=pip state=latest

   - name: ensure pexpect is installed
     pip: name=pexpect version=3.3

   - name: get globus repo rpm
     get_url: url=http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm dest=/tmp/globus-repo.rpm

   - name: get globus gpg key
     rpm_key: state=present key=http://toolkit.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus

   - name: install globus repo
     yum: name=/tmp/globus-repo.rpm state=present

   - name: install globus-connect-server
     yum: name=globus-connect-server state=present enablerepo=base

